### ISSUE TITLE
Changes and buffs to mobs also affect non-hostile mobs like animals

### ISSUE THREAD

**Issue by jacobmoerch** [Globox1997/RpgDifficulty#15]
As the title says, the modifications made by this mod also changes animals and other non-hostile animal. This is an unwanted effect.

**Comment by Globox1997** [comment]
it is intended from my side but you can put the mobs you don't want to be affected into the excluding list like:
"minecraft.cow"

**Comment by whuang3015** [comment]
I encountered a related issue here with bees. When they "go to sleep" for the night, it seems like they don't actually disappear in to the hive. Their entity seems to be transported somewhere far away, and back again upon reappearance the next day, doubling their HP each time. I ended up with an absolute god of a bee with millions of health and damage. I've seen similar things happen to 10k hp cows, but nothing as extreme as bees since they always disappear and reappear each day. I'm concerned that there's some memory issue that might eventually occur when their HP value gets too large. Encountered this on rpgdifficulty-1.2.0 with fabric-api-0.58.0+1.19.jar and MC version (1.19)

**Comment by marianyp** [comment]
> I encountered a related issue here with bees. When they "go to sleep" for the night, it seems like they don't actually disappear in to the hive. Their entity seems to be transported somewhere far away, and back again upon reappearance the next day, doubling their HP each time. I ended up with an absolute god of a bee with millions of health and damage. I've seen similar things happen to 10k hp cows, but nothing as extreme as bees since they always disappear and reappear each day. I'm concerned that there's some memory issue that might eventually occur when their HP value gets too large. Encountered this on rpgdifficulty-1.2.0 with fabric-api-0.58.0+1.19.jar and MC version (1.19)

I'm encountering a similar issue. In my world there was a bee with 10,000,000 health.

**Comment by Globox1997** [comment]
Fixed the bees issue with a later update.
For excluding entities, please use the excluding list.
