### ISSUE TITLE
it dont work

### ISSUE THREAD

**Issue by githubbingitup** [Globox1997/RpgDifficulty#2]
hi love your mod but having some issues. tried last two versions of fabric api for minecraft 1.16.5. using rpgdifficulty-1.0.4.jar

1. setting time increase from 30 to 0 causes worlds to hang on load. not big issue since you can change time factor instead.

2. distance simply does not work. tried setting it to 1 block and going anywhere from a hundred to ten mill blocks out. mobs are identical. time scaling works fine. not using any other mods.

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest mc version but it should be fixed in mod version 1.0.6 which is for mc 1.17
[https://github.com/Globox1997/RpgDifficulty/commit/1543a1182c9346547701607f3c5bd13a5052d163](https://github.com/Globox1997/RpgDifficulty/commit/1543a1182c9346547701607f3c5bd13a5052d163)

**Comment by githubbingitup** [comment]
Wow awesome !!! u rock :D i cant wait to try it
none of the other rpg mods are 1.17 yet, are we able to use this new version on 1.16.5 too ??

thx for ur great work, i use so many of ur mods!

**Comment by Globox1997** [comment]
I actually don't know if you can use it on 1.16.5 but I guess you can't..
thank you and you are welcome
